### ISSUE TITLE
Cataclysm Checklist

### ISSUE THREAD

**Issue by BreakBB** [Questie/Questie#5784]
# TODOs

## Fundamental
- [x] Add a first set of data (quests, NPCs, items and objects)
- [x] Load corrections
- [x] Remove previous corrections from loading in `Questie-Cata.toc`
- [x] Remove wotlk DB from loading in `Questie-Cata.toc`
- [x] Fix zones containing multiple icons of the same NPC
- [x] Add new zones to zoneDB (or replace them entirely?)
- [x] Add spawns for NPCs and objects in new zones
- [x] Find a solution for all these zone-Phases
    - https://old.wow.tools/dbc/?dbc=phase&build=4.3.4.15595#page=9
    - `creature.phaseMask`
    - `phase_definitions` (is empty 😢 )
    - https://talk.trinitycore.org/t/questions-about-object-player-phasing/29609
    - https://github.com/TrinityCore/TrinityCore/issues/12715
- [x] Add `Questie.IsCata` once Blizzard adds it
- [x] Add blacklisting logic
- [x] Add Cata Townsfolk data
- [x] Blacklist all cata event quests

## Should be fixed soon
- [x] Tracker hides `WatchFrameAutoQuestPopUp1`
- [x] Add event quests to `QuestieEvent.lua`
- [x] Reputation rewards
    - The cata data uses [QuestFactionReward.dbc](https://wago.tools/db2/QuestFactionReward)
- [x] Add new Dungeon/Raid locations
- [x] ~~Remove post cata NPCs (check around ID 50827)~~ Looks like wowhead might be wrong 🤷🏻
- [x] Add cata quest XP
- [x] Add lookup data for the new cata related things

## Fix when there is time
- [ ] The two versions of "Off to the Bank" (https://www.wowhead.com/quest=26711/off-to-the-bank & https://www.wowhead.com/quest=26712/off-to-the-bank) are gender specific. Questie can not handle that atm.
- [ ] There are objects without names, but with spawn data (check ID 193096+)
- [ ] #6001
- [x] Respect the guild perk "Mr. Popularity" (reputation bonus)

## Minimap Tracking
- [x] ~~Connect Townsfolk options with the default Minimap tracking~~
    - ~~So e.g. "Class Trainer" disables both the Blizzard one and the Questie one~~ --> Not worth investing time at this point

## Libs
- [x] Update HereBeDragons so the icons on the continent level are positioned properly
- [x] Update Krowi WorldMapButton to fix missing `RefreshOverlayFrames`
    - Fixed on Blizzards side

**Comment by BreakBB** [comment]
For Phasing `Phasing.lua` was added which will be completed step by step as it is not easy to identify which quest starts which phase.

**Comment by BreakBB** [comment]
For the `HereBeDragons` update I contacted the author, but without beta access it will be hard to update.
