### ISSUE TITLE
Replace luacheck with LLS

### ISSUE THREAD

**Issue by BreakBB** [Questie/Questie#6684]
### Description

[lua-language-server](https://github.com/LuaLS/lua-language-server) (LLS) allows for far stricter and more detailed types than `luacheck`, which will overall improve the maintainability of Questie.

## TODOs
- [ ] Find out what is required to run LLS in a GitHub action
- [ ] Transform the `.luacheckrc` file to the `.luarc.json` [format](https://luals.github.io/wiki/configuration/)
- [ ] Find a proper way to use [LLS-Addons](https://luals.github.io/wiki/addons/) for existing type definitions (we might be able to use the types from https://github.com/Ketho/vscode-wow-api as well)
- [ ] Find out if a "big bang" switch is feasible or if it better to start by ignoring most locations and transform them step by step
- [ ] Test https://plugins.jetbrains.com/plugin/22315-sumnekolua for IntelliJ
  - Do regular IntelliJ shortcuts work?
  - Is it fast (enough)?

**Comment by BreakBB** [comment]
First test show: LLS is pretty slow and some configurations simply don't work at all 😐
